{% set name = "git-versioner" %}
{% set name_url = "git_versioner" %}
{% set version = "5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/{{ name[0] }}/{{ name }}/{{ name_url }}-{{ version }}-py3-none-any.whl
  sha256: 776f511221ac7352f03ef15187e7e3d81cd07d2caa93ff4d98fe77c68471f6c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps {{ name_url }}-{{ version }}-py3-none-any.whl -vv
  number: 0
  entry_points:
    - git-versioner = __version__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools

about:
  home: https://gitlab.com/alelec/__version__
  summary: Manage current / next version for project
  description: |
    git-versioner manages the version number for the project based on git tags.
    The goal of this packages versioning scheme is to avoid ever needing to
    manually create versions numbers or update version details in files that
    need to be committed to the repository.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://gitlab.com/alelec/__version__

extra:
  recipe-maintainers:
    - adament
