{% set name = "git-versioner" %}
{% set name_url = "git_versioner" %}
{% set version = "5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/{{ name[0] }}/{{ name }}/{{ name_url }}-{{ version }}-py3-none-any.whl
  sha256: 2208c3e4353c3af5c0089b3841d12be051f78ec74dc55cd34f4d877ab2674cf4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps {{ name_url }}-{{ version }}-py3-none-any.whl -vv
  number: 0
  entry_points:
    - git-versioner = __version__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools

test:
  commands:
    - git-versioner -h

about:
  home: https://gitlab.com/alelec/__version__
  summary: Manage current / next version for project
  description: |
    git-versioner manages the version number for the project based on git tags.
    The goal of this packages versioning scheme is to avoid ever needing to
    manually create versions numbers or update version details in files that
    need to be committed to the repository.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://gitlab.com/alelec/__version__

extra:
  recipe-maintainers:
    - adament
